--SQL Server: Boas práticas em bancos relacionais
-------------------------------------------------------------
-------------------------------------------------------------

--O funcionamento de um banco de dados - Parte 1
--O funcionamento de um banco de dados - Parte 2

CREATE TABLE PRODUTOS 
(
	CODIGO			INT			NOT NULL,
	DESCRICAO		VARCHAR(50) NOT NULL,
	DATA_VALIDADE	DATETIME,
	EAN				VARCHAR(15) NOT NULL,
	IND_INATIVO		INT			NOT NULL DEFAULT 0
)
;

ALTER TABLE PROSUTOS
	ADD CONSTRAINT PK_PRODUTOS
		PRIMARY KEY (CODIGO)
;

--Como criar índices e realizar inserts
CREATE INDEX IDX01_PRODUTOS
			ON PRODUTOS(EAN)
;

INSERT INTO PRODUTOS VALUES (1, 'Nome do Produto', GETDATE(), '9780201379', 0);

--Realizando inserts em campos específicos

INSERT INTO PRODUTOS (CODIGO, DESCRICAO, EAN) VALUES (2, 'Nome do Produto 2', '1234567890');

SELECT * FROM PRODUTOS;

SELECT * 
  FROM PRODUTOS
 WHERE CODIGO = 2;

---- Consulta não indexada
SELECT * 
  FROM PRODUTOS
 WHERE DESCRICAO LIKE '%Produto'; --Trazer qualquer coisa que termine com Produto

 SELECT * 
  FROM PRODUTOS
 WHERE DESCRICAO LIKE '%Produto%'; --Trazer Produto em qualquer parte do texto


--Implementando funcionalidades

 SELECT COUNT(*) AS TOTAL
   FROM PRODUTOS


--Criando a tabela ESTOQUE
CREATE TABLE LOJAS
(
	CODIGO			INT			NOT NULL,
	NOME			VARCHAR(50)	NOT NULL,
	IND_INATIVO		INT			NOT NULL DEFAULT 0,
	CONSTRAINT LOJAS_PK PRIMARY KEY (CODIGO)
);

INSERT INTO LOJAS (CODIGO, NOME) VALUES (1000, 'Filial Nova Fortaleza');
INSERT INTO LOJAS (CODIGO, NOME) VALUES (2000, 'Filial São Paulo');
INSERT INTO LOJAS (CODIGO, NOME) VALUES (3000, 'Filial Crateus');

SELECT CODIGO,
	   NOME
  FROM LOJAS
  WHERE IND_INATIVO = 0;

CREATE TABLE ESTOQUE
(
	CODIGO_PRODUTO	INT		NOT NULL,
	CODIGO_FILIAL	INT		NOT NULL,
	QUANTIDADE		DECIMAL	NOT NULL DEFAULT 0,
	CONSTRAINT ESTOQUE_PK PRIMARY KEY (CODIGO_PRODUTO, CODIGO_FILIAL)
);

--Finalizando alterações nas tabelas segundo boas práticas

--ESTA ERRADO
INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES(99, 10, 1);

DELETE FROM ESTOQUE;

--DROP TABLE ESTOQUE;

ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
		FOREIGN KEY (CODIGO_PRODUTO)
		REFERENCES PRODUTOS(CODIGO)
;

ALTER TABLE ESTOQUE
	ADD CONSTRAINT FK_ESTOQUE_LOJAS
		FOREIGN KEY (CODIGO_FILIAL)
		REFERENCES LOJAS(CODIGO)
;

INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES(1, 1000, 10);

SELECT E.CODIGO_FILIAL,
       L.NOME	
  FROM ESTOQUE E INNER JOIN LOJAS L
    ON E.CODIGO_FILIAL = L.CODIGO
	INNER JOIN PRODUTOS P
	ON E.CODIGO_PRODUTO = P.CODIGO;
-------------------------------------------------------------
-------------------------------------------------------------