--SQL Server: Boas práticas em bancos relacionais

CREATE TABLE PRODUTOS 
(
	CODIGO			INT			NOT NULL,
	DESCRICAO		VARCHAR(50) NOT NULL,
	DATA_VALIDADE	DATETIME,
	EAN				VARCHAR(15) NOT NULL,
	IND_INATIVO		INT			NOT NULL DEFAULT 0
)